main: rpgcore.main.RPGCore
version: 3.5
name: RPGCore
depend: [WorldEdit]

commands:
  area:
    description: Core area management command
  sound:
    description: Plays a sound
  skills:
    description: Opens up your skillbook
    aliases: [s]
  class:
    description: Opens up your class manager
    aliases: [c]
  bgm:
    description: Plays a song
  item:
    description: Edits attributes/stats of an item
  party:
    description: Manages your party
  stats:
    description: Checks your stats
  boss:
    description: Spawns a boss for testing
  mob:
    description: Spawns a mob for testing
  crystal:
    description: Spawns crystals for testing
  npc:
    description: Test npc
  si:
    description: Saves the item as an item
  gi:
    description: Gets a saved item
  shop:
    description: Test-opens a shop
  rr:
    description: Reloads data
  gold:
    aliases: g
    description: Gold command
  convo:
    description: NPC Conversation command
  pc:
    description: Toggles a chest between preview and normal type