main: rpgcore.main.RPGCore
version: 4.1
name: RPGCore
depend: [WorldEdit]

commands:
  eq:
    description: Peek into someone else's equipment
  colors:
    description: Lists all colors
  area:
    description: Core area management command
  arena:
    description: Core arena management command
  testsound:
    description: Plays a sound
  skills:
    description: Opens up your skillbook
    aliases: [s, m]
  class:
    description: Opens up your class manager
    aliases: [c]
  bgm:
    description: Plays a song
  item:
    description: Edits attributes/stats of an item
  party:
    description: Manages your party
  mob:
    description: Spawns a mob for testing
  mobdrops:
    description: Opens up mob drops for specific mobs
  crystal:
    description: Spawns crystals for testing
  npc:
    description: Test npc
  saveitem:
    aliases: si
    description: Saves the item as an item
  getitem:
    aliases: gi
    description: Gets a saved item
  shop:
    description: Test-opens a shop
  rr:
    description: Reloads data
  gold:
    aliases: g
    description: Gold command
  convo:
    description: NPC Conversation command
  pc:
    description: Toggles a chest between preview and normal type
  npcflag:
    description: Edits player NPC flags for testing
  skillbook:
    aliases: sb
    description: Obtains a skillbook for a skill
  skull:
    description: Get sum custom skulls
  itemfood:
    aliases: if
    description: Edits attributes/stats of a food item
  itemprice:
    description: Sets the price of an item
  buffs:
    aliases: [b, stats]
    description: Checks your buffs
  enhance:
    description: Opens up the item enhancement UI